# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-09-12T11:57:37+00:00

from __future__ import annotations

from fastapi import Depends, FastAPI

from .core import post_example_core
from .models import RequestExample, ResponseExample

app = FastAPI(title="DVC FastAPI Example", version="0.0.1", openapi_url="/openapi.json")


@app.post('/', response_model=ResponseExample)
def post_example(body: RequestExample) -> ResponseExample:
    """
    post example
    """
    response = post_example_core(body)
    return response
