openapi: 3.0.2
info:
  title: DVC FastAPI Example
  version: 0.0.1
paths:
  "/":
    post:
      summary: post example
      operationId: post_example
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/request_example"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/response_example"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    request_example:
      title: request example
      required:
      - pclass
      - sex
      - age
      type: object
      properties:
        pclass:
          title: Pclass
          type: string
        sex:
          title: Sex
          type: string
        age:
          title: Age
          type: number
    response_example:
      title: response example
      required:
      - survived
      type: object
      properties:
        survived:
          title: Survived
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string